<x-admin-layout>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam possimus iusto vitae, nemo, inventore est distinctio iste itaque explicabo repellat maiores illo non rerum quae dolor quo tenetur asperiores accusamus!</p>
    </x-admin-layout>